FROM ubuntu:21.04

LABEL SOFTWARE_NAME marbl/merqury
LABEL MAINTAINER "Tom Harrop"
LABEL VERSION "v1.3"

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C
ENV PATH="${PATH}:/meryl/bin"

RUN     apt-get clean && \
        rm -r /var/lib/apt/lists/*

RUN     . /etc/os-release \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME} main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-updates main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-backports main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-security main restricted universe multiverse" >> mirror.txt && \
        mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
        cat mirror.txt /etc/apt/sources.list.bak > /etc/apt/sources.list && \
        apt-get update && \
        apt-get install -y ca-certificates && \
        apt-get upgrade -y --fix-missing

RUN     apt-get update && apt-get install -y  --no-install-recommends \
            bedtools \
            build-essential \
            default-jre \
            git \
            r-cran-argparse \
            r-cran-ggplot2 \
            r-cran-scales \
            samtools \
            wget

RUN     git clone https://github.com/marbl/meryl.git /meryl
WORKDIR /meryl
RUN     git checkout -f v1.3 && \
        git submodule update --init --recursive

WORKDIR /meryl/src
RUN     make

RUN     meryl --help

ENV     MERQURY=/merqury

WORKDIR /
RUN     git clone https://github.com/marbl/merqury.git /merqury
WORKDIR /merqury
RUN     git checkout -f v1.3 && \
        git submodule update --init --recursive

RUN     /merqury/merqury.sh

ENTRYPOINT ["/merqury/merqury.sh"]